### ISSUE TITLE
think about dynamic(compiler and class loading) 

### ISSUE THREAD

**Issue by presly808** [presly808/StudyArt#13]
draw architecture of task runner with test data(see 3)

**Comment by df413** [comment]
What about JavaCompiler via getSystemJavaCompiler?
Also we can add possibility to use codingbat.com compiler for their tasks, so we just need to generate simple urlencoded POST to http://codingbat.com/run like:
id=p186759
code=""
cuname=""
owner=""
adate=""

**Comment by presly808** [comment]
it is cool!
write full example of using this post method
and attach documentation where you got this information

for comfortable testing POST use https://chrome.google.com/webstore/detail/dhc-resthttp-api-client/aejoelaoggembcahagimdiliamlcdmfm

but in future write own DynamicCompiler!

thank you for research)

**Comment by presly808** [comment]
from dhc cleint, link in above comment

Example for http post request, it will simplify our task of grabbing test data, we will not use Selenium

![image](https://cloud.githubusercontent.com/assets/6671836/11023222/41b0de96-867b-11e5-84ad-c338c84975ae.png)
